version: "3.4"
services:
    intro_events:
        container_name: intro_events
        build: './intro'
        restart: always
        environment:
            - MJ_APIKEY_PRIVATE=${MJ_APIKEY_PRIVATE}
            - MJ_APIKEY_PUBLIC=${MJ_APIKEY_PUBLIC}
            - MONGODB_STRING=${MONGODB_STRING}
            - recaptcha=${recaptcha}
        # ports: 
        #     - 8080:3000
        expose:
            - 3000
        labels:
            - traefik.enable=true
            - traefik.http.routers.microsites_insecure.entrypoints=web
            - traefik.http.routers.microsites_insecure.rule=Host(`intro.events.poiw.org`)
            - traefik.http.routers.microsites_insecure.middlewares=redirect@file
            - traefik.http.routers.microsites.entrypoints=web-secure
            - traefik.http.routers.microsites.rule=Host(`intro.events.poiw.org`)
            - traefik.http.routers.microsites.tls.certresolver=letsencrypt
            - traefik.http.services.microsites.loadbalancer.server.port=3000
            - traefik.docker.network=traefik-proxy    
        networks:
            - traefik-proxy
            - default
networks:
  traefik-proxy:
    external: true
