# This is a basic workflow to help you get started with Actions

name: Deploy server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [cas-update]

jobs:
  Hermes:
    runs-on: ['hermes']
    env:
        MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
        MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
        MONGODB_STRING: ${{ secrets.MONGODB_STRING }}
        recaptcha: ${{ secrets.recaptcha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          submodules: true
      - name: Build docker images
        run: docker-compose build
      - name: Deploy
        run: docker-compose up -d
  Calliroe:
    runs-on: ['calliroe']
    env:
        MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
        MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
        MONGODB_STRING: ${{ secrets.MONGODB_STRING }}
        recaptcha: ${{ secrets.recaptcha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          submodules: true
      - name: Build docker images
        run: docker-compose build
      - name: Deploy
        run: docker-compose up -d


