# This is a basic workflow to help you get started with Actions

name: Deploy server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Stop running containers
        run: docker-compose down --remove-orphans
      - name: Build docker images
        run: docker-compose build
      - name: Deploy
        run: docker-compose up -d
